# Generated by Django 5.1.2 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_questiongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="audio_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="audio_mime",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image_mime",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
